language: cpp
os: osx
compiler: clang

install:
  - pip install --user nose
  - pip install --user cpp-coveralls
  
script:
    - mkdir .build
    - cd .build
    - cmake ..
    - cmake --build .

after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
